//PROJ_DIR = "~/public_html/AmbientVisualizations/Spring-2018/";
//PROJ_DIR = "~/public_html";
KITCHEN_IMAGES_PATH = "http://sysnet.cs.williams.edu/~20gem3/Water_Story/labeled-kitchen/";
//CIRCLES_IMAGES_PATH = PROJ_DIR + "images/circles/";
//LABELED_CIRCLES_IMAGES_PATH = PROJ_DIR + "images/labeled_circles/";
//PINWHEELS_IMAGES_PATH = PROJ_DIR + "images/pinwheels/";
//HEXAGONS_IMAGES_PATH = PROJ_DIR + "images/hexagons/";
//SCRIPTS_PATH = PROJ_DIR + "scripts/";
COOKING_PATH = "http://sysnet.cs.williams.edu/~20gem3/Water_Story/cooking/";
